[features]
seeds = false
[programs.devnet]
contract = "B6Xs1NbTwCSDZqFoQys3QW6XSKY6jejR67gfHjEaWCva"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/andreyminin/.config/solana/id.json"

[scripts]
test = "node tests/contract.js"
